#@ load("@ytt:data", "data")
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: #@ data.values.projectName
  description: #@ data.values.description
  tags:
    - golang
  links:
    - url: https://go.dev
      title: GoLang
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=golang-accelerator"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: denmark-team
  system: demo


